[build]
  publish = "final_real_sources_linked/netlify-deploy-real-api"
  functions = "final_real_sources_linked/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsdom", "google-trends-api", "xml2js"]

# 把前端原本會取用的 data/*.json，導到 Functions
[[redirects]]
  from = "/data/taiwan-keywords.json"
  to = "/.netlify/functions/stock-trends"
  status = 200
  force = true

[[redirects]]
  from = "/data/industry-news.json"
  to = "/.netlify/functions/news?mode=industry"
  status = 200
  force = true

[[redirects]]
  from = "/data/us-economic-news.json"
  to = "/.netlify/functions/news?mode=us_economic"
  status = 200
  force = true

[[redirects]]
  from = "/data/us-indices.json"
  to = "/.netlify/functions/usindices"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
