[build]
  publish = "final_real_sources_linked/netlify-deploy-real-api"
  functions = "final_real_sources_linked/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["xml2js", "jsdom", "google-trends-api"]

# 讓前端原本 fetch 的 data/*.json 自動導到 Functions
[[redirects]]
  from = "/data/taiwan-keywords.json"
  to = "/.netlify/functions/stock-trends?mode=tw"
  status = 200
  force = true

[[redirects]]
  from = "/data/industry-news.json"
  to = "/.netlify/functions/news?mode=industry"
  status = 200
  force = true

[[redirects]]
  from = "/data/us-economic-news.json"
  to = "/.netlify/functions/news?mode=us_economic"
  status = 200
  force = true

[[redirects]]
  from = "/data/us-indices.json"
  to = "/.netlify/functions/usindices"
  status = 200
  force = true

# SPA fallback（避免內頁重新整理變 404）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 基本快取（可照你需求再調）
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
